'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { deactivateAdminDriver, updateAdminDriver, type DriverDetail } from './admin-drivers-api';
import { getApiErrorFeedback } from '@/lib/api-error-feedback';
export function DriverAdminActions({driver}:{driver:DriverDetail['driver']}){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();router.refresh();}catch(e){setError(getApiErrorFeedback(e).message);}finally{setBusy(false);}}return <div className="flex flex-wrap gap-2"><Dialog><DialogTrigger asChild><Button variant="ghost">ویرایش راننده</Button></DialogTrigger><DialogContent title="ویرایش راننده" description="اطلاعات تماس و نشانی راننده را اصلاح کنید."><form className="grid gap-4" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void run(()=>updateAdminDriver(driver.id,Object.fromEntries(data.entries()) as Record<string,string>));}}><label className="text-sm font-bold">همراه دوم<Input name="secondaryPhoneNumber" defaultValue={String(driver.secondaryPhoneNumber??'')} className="mt-2"/></label><label className="text-sm font-bold">تلفن منزل<Input name="homePhoneNumber" defaultValue={String(driver.homePhoneNumber??'')} className="mt-2"/></label><label className="text-sm font-bold">نشانی<Input name="streetAddress" defaultValue={String(driver.streetAddress??'')} className="mt-2"/></label><Button loading={busy}>ذخیره تغییرات</Button>{error&&<p role="alert" className="text-xs text-danger">{error}</p>}</form></DialogContent></Dialog>{driver.status!=='INACTIVE'&&<Button variant="ghost" className="text-danger" loading={busy} onClick={()=>{if(window.confirm('راننده و مسیرهای فعال او غیرفعال شوند؟'))void run(()=>deactivateAdminDriver(driver.id));}}>حذف راننده</Button>}</div>}
