'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Search, Users } from 'lucide-react';
import { Alert } from '@/components/feedback/alert';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import type { AdminSchool } from '@/features/admin-schools/admin-schools-api';
import type { AdminStudent } from '@/features/admin-students/admin-students-api';
import { addStudentToAdminRoute, archiveAdminRoute, createAdminTransportRoute, removeStudentFromAdminRoute, type AdminTransportRoute, type DriverListItem } from './admin-drivers-api';

export function RouteManagement({ routes, drivers, schools, students }: { routes:AdminTransportRoute[];drivers:DriverListItem[];schools:AdminSchool[];students:AdminStudent[] }) {
  const router = useRouter(); const [query,setQuery]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string>();
  const visible=useMemo(()=>routes.filter((route)=>`${route.title} ${route.school.name} ${route.driver?.firstName ?? ''} ${route.driver?.lastName ?? ''}`.includes(query.trim())),[routes,query]);
  async function create(data:FormData){setBusy(true);setMessage(undefined);try{await createAdminTransportRoute({driverId:String(data.get('driverId')),schoolId:String(data.get('schoolId')),title:String(data.get('title')),academicYear:String(data.get('academicYear')),direction:String(data.get('direction')) as 'TO_SCHOOL'|'FROM_SCHOOL',scheduledStartTime:String(data.get('scheduledStartTime')),scheduledArrivalTime:String(data.get('scheduledArrivalTime')),areaDescription:String(data.get('areaDescription')??''),activeWeekdays:data.getAll('activeWeekdays').map(Number)});setMessage('مسیر جدید ایجاد شد.');router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'ایجاد مسیر انجام نشد.')}finally{setBusy(false)}}
  async function add(routeId:string,data:FormData){setBusy(true);setMessage(undefined);try{await addStudentToAdminRoute(routeId,{studentId:String(data.get('studentId')),scheduledStopTime:String(data.get('scheduledStopTime')),pickupOrder:Number(data.get('pickupOrder')),notes:String(data.get('notes')??'')});setMessage('دانش‌آموز به مسیر افزوده شد و اطلاع‌رسانی انجام شد.');router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'افزودن دانش‌آموز انجام نشد.')}finally{setBusy(false)}}
  async function remove(routeId:string,studentId:string){setBusy(true);setMessage(undefined);try{await removeStudentFromAdminRoute(routeId,studentId);setMessage('دانش‌آموز از مسیر حذف شد و اطلاع‌رسانی انجام شد.');router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'حذف ارتباط انجام نشد.')}finally{setBusy(false)}}
  async function archive(routeId:string){setBusy(true);setMessage(undefined);try{await archiveAdminRoute(routeId);setMessage('مسیر غیرفعال شد.');router.refresh()}catch(error){setMessage(error instanceof Error?error.message:'غیرفعال‌کردن مسیر انجام نشد.')}finally{setBusy(false)}}
  return <div className="space-y-6">{message&&<Alert title="نتیجه عملیات">{message}</Alert>}<Card><h2 className="text-lg font-black">ساخت مسیر جدید</h2><p className="mt-1 text-sm text-muted">هر مسیر متعلق به یک راننده، یک خودرو و یک مدرسه است.</p><form action={create} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="عنوان مسیر"><Input name="title" required placeholder="مثلاً مسیر سعادت‌آباد" /></Field><Field label="راننده"><Select name="driverId" items={drivers.map(d=>({value:d.id,label:`${d.firstName} ${d.lastName} · ${d.plateNumber??'بدون پلاک'} · ظرفیت ${d.capacity??0}`}))}/></Field><Field label="مدرسه"><Select name="schoolId" items={schools.filter(s=>s.isActive).map(s=>({value:s.id,label:s.name}))}/></Field><Field label="سال تحصیلی"><Input name="academicYear" defaultValue="۱۴۰۵-۱۴۰۶" required /></Field><Field label="جهت"><select name="direction" className="min-h-12 w-full rounded-xl border border-border bg-white px-3"><option value="TO_SCHOOL">رفت به مدرسه</option><option value="FROM_SCHOOL">برگشت از مدرسه</option></select></Field><Field label="شروع"><Input type="time" name="scheduledStartTime" defaultValue="07:00" required /></Field><Field label="پایان"><Input type="time" name="scheduledArrivalTime" defaultValue="07:30" required /></Field><Field label="محدوده"><Input name="areaDescription" placeholder="منطقه و محله‌های مسیر" /></Field><fieldset className="md:col-span-2 xl:col-span-3"><legend className="text-sm font-bold">روزهای فعال</legend><div className="mt-2 flex flex-wrap gap-3">{['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'].map((day,index)=><label key={day} className="flex items-center gap-1 text-sm"><input type="checkbox" name="activeWeekdays" value={index} defaultChecked={index<5}/>{day}</label>)}</div></fieldset><Button className="self-end" loading={busy}>ایجاد مسیر</Button></form></Card>
  <div className="relative max-w-xl"><Search className="absolute end-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pe-10" placeholder="جست‌وجو در نام مسیر، مدرسه یا راننده…"/></div>
  <div className="grid gap-5">{visible.map(route=>{const eligible=students.filter(s=>s.isActive&&s.schoolId===route.school.id&&!route.students.some(member=>member.id===s.id));const capacity=route.driver?.capacity??0;return <Card key={route.id}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black">{route.title}</h3><p className="text-sm text-muted">{route.driver?`${route.driver.firstName} ${route.driver.lastName}`:'راننده نامشخص'} · {route.school.name} · {route.scheduledStartTime} تا {route.scheduledArrivalTime}</p></div><div className="flex items-center gap-2"><span className="inline-flex h-9 items-center gap-2 rounded-full bg-primary-soft px-3 text-xs font-bold text-primary"><Users className="size-4"/>{route.students.length.toLocaleString('fa-IR')} از {capacity.toLocaleString('fa-IR')}</span><Button type="button" variant="ghost" size="sm" disabled={busy} onClick={()=>void archive(route.id)}>غیرفعال‌کردن</Button></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs">{route.students.map(student=><span key={student.id} className="inline-flex items-center gap-2 rounded-lg bg-surface-inset px-3 py-2">{student.pickupOrder.toLocaleString('fa-IR')}. {student.firstName} {student.lastName} · {student.scheduledStopTime??'بدون زمان'}<button type="button" onClick={()=>void remove(route.id,student.id)} disabled={busy} className="font-black text-danger" aria-label={`حذف ${student.firstName} ${student.lastName} از مسیر`}>×</button></span>)}</div><form action={data=>add(route.id,data)} className="mt-5 grid gap-3 border-t border-border pt-4 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_1fr_2fr_auto]"><Field label="دانش‌آموز"><Select name="studentId" items={eligible.map(s=>({value:s.id,label:`${s.firstName} ${s.lastName} · ${s.grade??'بدون پایه'}`}))}/></Field><Field label="زمان توقف"><Input type="time" name="scheduledStopTime" required /></Field><Field label="ترتیب"><Input type="number" min={1} name="pickupOrder" defaultValue={route.students.length+1} required /></Field><Field label="یادداشت"><Input name="notes" placeholder="توضیح اختیاری" /></Field><Button className="self-end" disabled={busy||!eligible.length||route.students.length>=capacity}>افزودن</Button></form></Card>})}</div></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold">{label}<span className="mt-2 block">{children}</span></label>}
function Select({name,items}:{name:string;items:Array<{value:string;label:string}>}){return <select name={name} required className="min-h-12 w-full rounded-xl border border-border bg-white px-3"><option value="">انتخاب کنید</option>{items.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select>}
