'use client';
import { useCallback, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { SearchPicker } from '@/components/ui/search-picker';
import { normalizeDigits } from '@/features/enrollment/national-id';
import type { AdminSchool } from '@/features/admin-schools/admin-schools-api';
import { getAdminStudents, type AdminStudent } from '@/features/admin-students/admin-students-api';
import { getApiErrorFeedback } from '@/lib/api-error-feedback';
import { addStudentToAdminRoute, archiveAdminRoute, createAdminTransportRoute, removeStudentFromAdminRoute, updateAdminTransportRoute, type AdminTransportRoute, type DriverListItem } from './admin-drivers-api';
import { RouteCatalog } from './route-catalog';

export function RouteManagement({ routes, drivers, schools, students }: { routes:AdminTransportRoute[]; drivers:DriverListItem[]; schools:AdminSchool[]; students:AdminStudent[] }) {
  const router=useRouter(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const [schoolId,setSchoolId]=useState(''); const [filterSchoolId,setFilterSchoolId]=useState(''); const [routeId,setRouteId]=useState(''); const [studentId,setStudentId]=useState(''); const [choices,setChoices]=useState(students);
  const school=schools.find(s=>s.id===schoolId); const route=routes.find(r=>r.id===routeId);
  const visibleStudents=useMemo(()=>choices.filter(s=>!filterSchoolId||s.schoolId===filterSchoolId),[choices,filterSchoolId]);
  async function perform(action:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');try{await action();setMessage(success);router.refresh();}catch(error){setMessage(getApiErrorFeedback(error).message);}finally{setBusy(false);}}
  const studentLabel=(s:AdminStudent)=>`${s.firstName} ${s.lastName} · ${s.schoolName??''}${s.companion?' · دارای همراه (۲ صندلی)':''}`;
  const searchStudents=useCallback(async(q:string)=>{const result=await getAdminStudents({q,archive:'active',pageSize:100});const rows=result.students.filter(s=>!filterSchoolId||s.schoolId===filterSchoolId);setChoices(current=>[...new Map([...current,...rows].map(s=>[s.id,s])).values()]);return rows.map(s=>({value:s.id,label:`${s.firstName} ${s.lastName} · ${s.schoolName??''}${s.companion?' · دارای همراه (۲ صندلی)':''}`}));},[filterSchoolId]);
  async function create(data:FormData){if(!school)return;const end=[...school.closingTimes,school.closingTime].filter(Boolean).sort().at(-1)??school.closingTime;await perform(()=>createAdminTransportRoute({title:String(data.get('title')),driverId:String(data.get('driverId')),schoolId:school.id,academicYear:String(data.get('academicYear')),direction:String(data.get('direction')) as AdminTransportRoute['direction'],scheduledStartTime:school.openingTime,scheduledArrivalTime:end,contractPriceRials:Number(data.get('contractPriceRials')),contractDate:normalizeDigits(String(data.get('contractDate'))),activeWeekdays:[0,1,2,3,4]}),'مسیر با ساعت‌های مدرسه ایجاد شد.');}
  async function add(data:FormData){if(!route||!studentId)return;const student=choices.find(item=>item.id===studentId);await perform(()=>addStudentToAdminRoute(route.id,{studentId,scheduledStopTime:String(data.get('stopTime')),pickupOrder:route.students.length+1}),student?.companion?'دانش‌آموز و همراه او با مصرف دو صندلی به مسیر افزوده شدند.':'دانش‌آموز به مسیر افزوده شد.');}
  return <Card className="space-y-8">
    <section><h2 className="text-lg font-black">تعریف مسیر و تخصیص دانش‌آموز</h2><p className="mt-2 text-sm leading-7 text-muted">ساعت مسیر از ساعت شروع و آخرین ساعت پایان مدرسه خوانده می‌شود. فیلتر مدرسه فقط جست‌وجوی دانش‌آموز را آسان می‌کند؛ یک مسیر می‌تواند دانش‌آموزان چند مدرسه را داشته باشد.</p>
      <form onSubmit={e=>{e.preventDefault();void create(new FormData(e.currentTarget));}} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <Field label="عنوان مسیر"><Input name="title" required minLength={2}/></Field><Field label="راننده"><Picker name="driverId" options={drivers.filter(d=>d.status==='ACTIVE').map(d=>({value:d.id,label:`${d.firstName} ${d.lastName} · ظرفیت ${d.capacity??0}`}))}/></Field>
        <Field label="مدرسه مبنا"><Picker value={schoolId} onChange={setSchoolId} options={schools.filter(s=>s.isActive).map(s=>({value:s.id,label:s.name}))}/></Field><Field label="جهت"><Picker name="direction" options={[{value:'TO_SCHOOL',label:'رفت'},{value:'FROM_SCHOOL',label:'برگشت'},{value:'ROUND_TRIP',label:'رفت و برگشت'}]}/></Field>
        <Field label="شروع مدرسه"><Input value={school?.openingTime??''} readOnly/></Field><Field label="پایان مدرسه"><Input value={school?([...school.closingTimes,school.closingTime].filter(Boolean).sort().at(-1)??''):''} readOnly/></Field><Field label="سال تحصیلی"><Input name="academicYear" defaultValue="1405-1406" required/></Field><Field label="مبلغ قرارداد ماهانه مسیر (ریال)"><Input name="contractPriceRials" type="number" min="0" step="1" required inputMode="numeric"/></Field><Field label="تاریخ قرارداد (شمسی)"><Input name="contractDate" placeholder="1405/06/22" pattern="1[34][0-9]{2}/(0[1-9]|1[0-2])/(0[1-9]|[12][0-9]|3[01])" required dir="ltr"/></Field><Button className="self-end" loading={busy} disabled={busy||!school}>ایجاد مسیر</Button>
      </form></section>
    <section className="border-t border-border pt-7"><h3 className="font-black">مدیریت دانش‌آموزان مسیر</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="مسیر"><Picker value={routeId} onChange={setRouteId} options={routes.map(r=>({value:r.id,label:`${r.title} · ${r.school.name}`}))}/></Field><Field label="فیلتر مدرسه دانش‌آموز"><Picker value={filterSchoolId} onChange={v=>{setFilterSchoolId(v);setStudentId('');}} required={false} options={schools.map(s=>({value:s.id,label:s.name}))}/></Field></div>
      <form onSubmit={e=>{e.preventDefault();void add(new FormData(e.currentTarget));}} className="mt-4 grid gap-4 md:grid-cols-2"><SearchPicker label="دانش‌آموز" loadOptions={searchStudents} value={studentId} onChange={setStudentId} options={visibleStudents.map(s=>({value:s.id,label:studentLabel(s)}))}/><Field label="زمان توقف"><Input key={routeId} name="stopTime" type="time" required defaultValue={route?.scheduledStartTime.slice(0,5)}/></Field><Button disabled={busy||!route||!studentId} loading={busy}>افزودن به مسیر</Button></form>
      {route?.students.length?<ul className="mt-5 divide-y divide-border rounded-xl border border-border">{route.students.map(student=><li key={student.id} className="flex min-h-14 items-center justify-between gap-3 px-4"><span className="text-sm font-bold">{student.pickupOrder}. {student.firstName} {student.lastName}{student.companion&&<small className="mr-2 rounded-full bg-warning-soft px-2 py-1 text-warning">همراه: {student.companion.firstName} {student.companion.lastName} · ۲ صندلی</small>}</span><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={()=>void perform(()=>removeStudentFromAdminRoute(route.id,student.id),'ارتباط دانش‌آموز و همراه او با مسیر حذف شد.')}>حذف از مسیر</Button></li>)}</ul>:null}
    </section>
    <RouteCatalog routes={routes} onEdit={(id,body)=>perform(()=>updateAdminTransportRoute(id,body),'مسیر ویرایش شد.')} onArchive={id=>perform(()=>archiveAdminRoute(id),'مسیر غیرفعال شد.')} busy={busy}/>{message&&<p role="status" className="rounded-xl bg-primary-soft p-3 text-sm font-bold">{message}</p>}
  </Card>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold">{label}<span className="mt-2 block">{children}</span></label>}
function Picker({name,value,onChange,options,required=true}:{name?:string;value?:string;onChange?:(value:string)=>void;options:{value:string;label:string}[];required?:boolean}){return <select name={name} value={value} onChange={e=>onChange?.(e.target.value)} required={required} className="min-h-12 w-full rounded-xl border border-border bg-white px-3"><option value="">{required?'انتخاب کنید':'همه مدارس'}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>}
